### ISSUE TITLE
installing this causes it to wipe my server modules

### ISSUE THREAD

**Issue by KarateSnoopy** [ScreepsMods/screepsmod-auth#14]
When I run
```
npm install screepsmod-auth
```

When its finished it says:
```
added 11 packages and removed 421 packages
```
which is clearly bad and means its deleting the screeps stand alone server modules.  I'm not sure of the cause or its just me but I can't shake the behavior.   I can work around by reinstalling screeps server again, but its kinda odd.

You can see it happen here:
https://youtu.be/UpPGEHSPJKo?t=8m49s

**Comment by KarateSnoopy** [comment]
Yeah, not sure cause.  Your other packages install with npm fine.  I tried a few times with this package and each time it removes the server modules for some odd reason.  I'm running npm v5.6

**Comment by ash-O-o** [comment]
I'm seeing the same thing. Very odd.
```
Screeps mod "screepsmod-auth" has been successfully installed
+ screepsmod-auth@2.4.6
added 12 packages from 19 contributors, removed 575 packages, updated 1 package and audited 240 packages in 51.552s
found 0 vulnerabilities
```

**Comment by ags131** [comment]
make sure you are doing `--save` when you install screeps, that should prevent npm from clearing them out, I'm closing this as screepsmod-auth doesn't do anything directly to cause packages to be removed.

**Comment by ash-O-o** [comment]
You know, that's probably it. I don't work with node much. >.>

**Comment by ash-O-o** [comment]
Following up: Completely a pebkac issue. `--save` fixed it. 👍
