### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by deathgaze** [ScreepsMods/screepsmod-auth#15]
Maybe I'm missing something. I ran the `npm install` command in the screeps/server folder and then I go into steam and start Client, and then click 'Start Server'. I use the client to log in and try to type `setPassword` in console and get an error: 
`
ReferenceError: setPassword is not defined
    at eval (eval at <anonymous> (_console1532738272209_0:1:46), <anonymous>:1:1)
    at _console1532738272209_0:1:46
    at _console1532738272209_0:1:60
    at Object.exports.evalCode (<isolated-vm>:15473:71)
    at Object.exports.run (<isolated-vm>:16920:41)
`
I'm running this on Mac OSX Steam, if that matters.

**Comment by ags131** [comment]
if using the steam server, install via steam workshop. The steam server overwrites the mods.json on every start effectively preventing manual mod installs :(

**Comment by deathgaze** [comment]
When using this with the steam client, I had to edit `.screepsrc` to point to a different `mods.json` file. I did this in order to stop the server from resetting the `mods.json` every time I tried to edit it. Looks like it's working now. :)
