### ISSUE TITLE
Setting Password via Web issue

### ISSUE THREAD

**Issue by cbacon93** [ScreepsMods/screepsmod-auth#20]
Hi, I just can't get the web passwort setting to work.
I am using screep- launcher on debian and safari as browser.

What I did so far:
I started my steam client and created an account
I navigated to server:21025/authmod/password and typed in my password
I pressed on "Sign in through steam"
Not I clicked on "Login" on the steam page
I get redirected to server:21025/api/auth/steam/return?somedata with a blank screen and the following html content:

```
<html>
<body>
    <script type="text/javascript">
    opener.postMessage(JSON.stringify({
        "username": "myusername",
        "token": "tokenstring",
        "steamid": "mysteamid"
    }), '*');
    window.close();
    </script>
</body>
```

I changed the token and steam id for data protection.
Of course my Browser complains that "opener" is null and my password didn't change.
Do you have any idea what went wrong? Maybe a missing JS file?

**Comment by ags131** [comment]
Fixed in 2.4.8, Safari apparently does some security stuff that disables `opener` by default on links with `target=_blank` like I use.
