### ISSUE TITLE
setPassword always returning undefined

### ISSUE THREAD

**Issue by pip** [ScreepsMods/screepsmod-auth#6]
I have removed everything from my mods.json file except example-mods/welcome-text.js and the default simplebot. Then I installed screepsmod-auth via the Steam Workshop. Restarting my Steam Screeps client and server, the launcher GUI says "Updating Workshop mods... - screepsmod-auth@2.1.1  Server version 2.8.2" but when I connect to localhost:21025, click into my W8N3 room, then open the Console tab and enter > "setPassword('MyDesiredPassword')" it just returns < "undefined" every time.

I thought there might be a conflict with some other mod so I went into the Workshop and removed all others and cleared out all examples but welcome, just to see if auth could possibly work in isolation. I would really like to become able to use the api/auth/signin to get a token for querying room-overview and market details, doing flag manipulation, and eventually to also be able to ssh in on port 21030 through screepsmod-remote-console.

Does anyone have any advice on what else I might try?

I'm running a regularly updated Ubuntu GNU/Linux 17.04 with kernel version 4.10.0-32-generic for x86_64. My best guess is that somehow my Steam client Workshop updater must be neglecting the correct version of some needed NPM prerequisite?

If someone can offer any insight into resolving my issue, I would be greatly appreciative.

Sincerely,
-Pip

**Comment by ags131** [comment]
`setPassword` will always return undefined when called, however, after that point it should be set and `/api/auth/signin` should work like normal.

**Comment by pip** [comment]
Hello ags131,

Thank you for you prompt response. I saw in the code and in the console output when just entering "setPassword" alone that it looks like it would log "Password Set". I'm sorry I mistakenly assumed I should expect that response on success.

After entering "setPassword('MyDesiredPassword')" in the console, I am then trying to go to my terminal program and enter `wget -O auth.json --post-data '{"email":"pipstuart@gmail.com","password":"MyDesiredPassword"}'  'http://localhost:21025/api/auth/signin'` but it returns ERROR 400: Bad Request.

Can you please tell me how it is supposed to work?

-Pip

**Comment by ags131** [comment]
you need the `Content-Type: application/json` header for it to recognize
JSON body

**Comment by ags131** [comment]
you can also use [node-screeps-api](https://github.com/screepers/node-screeps-api) or [python_screeps](https://github.com/screepers/python-screeps) for simpler access, [gulp-screeps](https://www.npmjs.com/package/gulp-screeps) or [grunt-screeps](https://www.npmjs.com/package/grunt-screeps) can be used for easy code upload

**Comment by pip** [comment]
Awesome! Thank you so much! That worked. Yay! =)

**Comment by ags131** [comment]
Np, glad I could help :)
