### ISSUE TITLE
Error return

### ISSUE THREAD

**Issue by yanchick** [ScreepsMods/screepsmod-auth#7]
Hi. I install mod via instruction. Then I pass `config.auth.authUser('yanchick','password')` to console i get:

`_console1504959358683_0:1
config.auth.authUser('yanchick','password')
^

ReferenceError: config is not defined
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at connectPromise.then.then (/app/node_modules/@screeps/driver/lib/runtime.js:296:18)`

What I do wrong?

**Comment by ags131** [comment]
You can't call that from console, you can call `setPassword('password')`
from the in game console though.

**Comment by yanchick** [comment]
When I do this I get 'undefined'. I want to push my code via grunt. That's why I set the password.

**Comment by ags131** [comment]
Its really should have a message instead, but undefined is the expected
result for that. Once that is called grunt should then work when pointed at
the server's IP (Or localhost if on same PC) on port 21025

**Comment by ags131** [comment]
I added a message in 7fb083e which will be in all future versions now. (Starting with 2.1.2)

**Comment by paul-wade** [comment]
I was really stuck on this 'why isn't it working' thanks for making this.
